server:
  port: 9201


spring:
  application:
    name: microsvc-canal-job
  kafka:
    bootstrap-servers: localhost:9092 #souke集群 10.15.5.4:9092 10.15.5.7:9092 10.15.4.182:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 1
#    properties:
#      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="r30" password="bhaCyq";
#      sasl.mechanism: PLAIN
#      security.protocol: SASL_PLAINTEXT
    listener:
      ack-mode: manual

    # 自定义业务topic属性
    xkt:
      groupid: group-canal-xkt
      topic: p1-xkt-mysql-canal
    material:
      groupid: group-canal-material
      topic: p1-material-mysql-canal
    igavin:
      groupid: group-canal-igavin
      topic: igavin-canal-test


microsvc:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      index:
        number-of-replicas: 0
        number-of-shards: 3



