version: '3'
services:
  skywalking-oap:
    image: apache/skywalking-oap-server:8.3.0-es7
    container_name: igavin-skywalking-oap
    networks:
      - igavin-net
      - igavin-skywalking-net
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200

  skywalking-ui:
    image: apache/skywalking-ui:8.3.0
    container_name: igavin-skywalking-ui
    networks:
      - igavin-skywalking-net
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 18080:8080
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: skywalking-oap:12800


networks:
  igavin-skywalking-net:
    external: false