server:
  port: 9101


spring:
  application:
    name: microsvc-web
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      datasource:
        flow:
          nacos:
            server-addr: 172.24.29.87:8848
            username: nacos
            password: nacos
            groupId: DEFAULT_GROUP
            dataId: microsvc-web-sentinel-flow-rules
            namespace: dev_igavin
            rule-type: flow
        degrade:
          nacos:
            server-addr: 172.24.29.87:8848
            username: nacos
            password: nacos
            groupId: DEFAULT_GROUP
            dataId: microsvc-web-sentinel-degrade-rules
            namespace: dev_igavin
            rule-type: degrade

      #eager: true



