version: '3'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: xxl_job_db
    ports:
      - 28889:3306
    volumes:
      #mysql数据库挂载到host物理机目录/e/docker/mysql/data/db
      - "../data/xxl-job/mysql:/var/lib/mysql"
      - "./xxl-job/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: xxl_job
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  admin:
    image: xuxueli/xxl-job-admin:2.1.2
    hostname: admin
    container_name: xxl_job
    ports:
      - 28888:8080
    links:
      - mysql
    volumes:
      - "../data/xxl-job/applogs:/data/applogs"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root
          --spring.datasource.password=123456'
    depends_on:
      - mysql
