# just example, not tested
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: ns-microsvc-app
  name: microsvc-ingress
spec:
  rules:
  - host:
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: microsvc-app
            port:
              number: 18081
  - host: app.igavin.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microsvc-app
            port:
              number: 18081
