apiVersion: v1
kind: Namespace
metadata:
  name: ns-microsvc-app

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: ns-microsvc-app
  name: cronjob-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-test
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsvc-app
  namespace: ns-microsvc-app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: microsvc-app
          image: igavin/microsvc-app:v1
          ports:
            - containerPort: 18081
              name: appport
          env:
            - name: log.dir
              value: /k8s-pod-log
            - name: spring.datasource.url
              # 这里的ip使用mysql的clusterIP
              value: jdbc:mysql://10.107.45.11:3306/mysql?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          volumeMounts:
            - name: log-dir
              mountPath: /k8s-pod-log

      volumes:
        - name: log-dir
          hostPath:
            path: /tmp/k8s-pod-log


---
apiVersion: v1
kind: Service
metadata:
  name: microsvc-app
  namespace: ns-microsvc-app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: svcappport
      protocol: TCP
      port: 18081
      targetPort: appport