apiVersion: v1
kind: Namespace
metadata:
  name: ns-microsvc-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsvc-app
  namespace: ns-microsvc-app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: microsvc-app
          image: igavin/microsvc-app:v1
          ports:
            - containerPort: 18081
              name: appport
          env:
            - name: log.dir
              value: ../data/log
            - name: spring.datasource.url
              # 这里的ip使用mysql的clusterIP
              value: jdbc:mysql://10.107.45.11:3306/mysql?characterEncoding=UTF-8&useUnicode=true&useSSL=false

---
apiVersion: v1
kind: Service
metadata:
  name: microsvc-app
  namespace: ns-microsvc-app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: svcappport
      protocol: TCP
      port: 18081
      targetPort: appport