version: "3"
services:
  prometheus-webhook-alert:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: igavin-prometheus-webhook-alertmanagers
    hostname: webhook-alertmanagers
    volumes:
      - /etc/localtime:/etc/localtime
      - ./grafana/alertmanager/dingtalk-config.yml:/etc/prometheus-webhook-dingtalk/config.yml
    ports:
      - "8060:8060"
    command: /bin/prometheus-webhook-dingtalk --ding.profile="webhook1=https://oapi.dingtalk.com/robot/send?access_token=3d75d489c8e57f3865f142d096bfa004834716192afb581049ecbee89dacf6a3"
    networks:
      - igavin-monitor

networks:
  igavin-monitor:
    external: false