version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: igavin-prometheus
    volumes:
      - ./grafana/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
    networks:
      - igavin-monitor

  node-exporter:
    image: prom/node-exporter:latest
    container_name: igavin-node-exporter
    ports:
      - "9100:9100"
    networks:
      - igavin-monitor

  grafana:
    image: grafana/grafana
    container_name: igavin-grafana
    ports:
      - "3000:3000"
    environment:
      - “GF_SECURITY_ADMIN_PASSWORD=Gz2020@”
      - “GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app”
    restart: "always"
    volumes:
      - ./data/grafana/logs:/var/logs/grafana
      - /etc/localtime:/etc/localtime
    depends_on:
      - prometheus
    networks:
      - igavin-monitor

networks:
  igavin-monitor:
    external: false