version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.4.1
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 需要把file.conf和registry.conf都放到./seata-server/config文件夹中
      - "./seata-server/config:/root/seata-config"