version: '3.0'
services:
  mysql3307:
    image: mysql:5.7
    ports:
      - "3307:3306"
    container_name: igavin-mysql-nacos-3307
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "./data/mysql3307/data:/var/lib/mysql"
    networks:
      - igavin-nacos-net


networks:
  igavin-nacos-net:
    external: false