server:
  port: 9201


spring:
  application:
    name: microsvc-canal-job
  kafka:
    bootstrap-servers: 10.15.5.4:9092 10.15.5.7:9092 10.15.4.182:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      #group-id: xkt-index-consumer
      enable-auto-commit: false
      #      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 1
    properties:
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="r30" password="bhaCyq";
      sasl.mechanism: PLAIN
      security.protocol: SASL_PLAINTEXT
    listener:
      ack-mode: manual

    # 自定义业务topic属性
    xkt:
      groupid: group-canal-xkt
      topic: p1-xkt-mysql-canal
    material:
      groupid: group-canal-material
      topic: p1-material-mysql-canal




