server:
  port: 9101

spring:
  application:
    name: microsvc-web
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      datasource:
        ds:
          nacos:
            server-addr: 172.24.29.87:8848
            username: nacos
            password: nacos
            groupId: DEFAULT_GROUP
            dataId: microsvc-web-sentinel
            namespace: dev_igavin
            rule-type: flow
      #eager: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.201.145.164:3306/mysql?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root123


mybatis:
  mapper-locations:
    - classpath*:mapper/*/*.xml
    - classpath*:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics,prometheus