apiVersion: v1
kind: Namespace
metadata:
  name: ns-igavin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
  namespace: ns-igavin
  labels:
    app: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      name: hellok8s
      labels:
        app: hellok8s
    spec:
      containers:
        - name: hellok8s-web
          image: igavin/microsvc-helloworld:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18080
              name: hellok8sport
---
apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
  namespace: ns-igavin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 18080
      protocol: TCP
  selector:
    app: hellok8s
